### Atribuição de Classe para 1.1 a 1.3
#### Crie uma matriz de tamanho (2,3) com valores binários aleatórios
#### Encontre a soma de todos os blocos 2x2 (sobrepostos) para uma matriz inteira aleatória de tamanho (3,5)

In [15]:
import numpy as np
m1 = np.random.randint(low=0, high=2, size=(2,3))
print('a matriz é: \n%s\n '%m1)

a matriz é: 
[[0 0 0]
 [1 0 1]]
 


In [16]:
m2 = np.random.randint(0,10,(3,5))
print('a matriz original é: \n%s\n' %m2)

a matriz original é: 
[[5 8 6 5 8]
 [7 3 0 8 0]
 [7 7 9 6 6]]



In [17]:
#criando a submatriz
subm2= m2[0:2,2:4]
subm3= m2[0:2,0:2]
subm4 = m2[1:3,3:5]
print('a submatriz é: \n%s\n' %subm2)
print('a submatriz é: \n%s\n' %subm3)
print('a submatriz é: \n%s\n' %subm4)
soma = np.sum([[subm2],[subm3],[subm4]])
print(soma)

a submatriz é: 
[[6 5]
 [0 8]]

a submatriz é: 
[[5 8]
 [7 3]]

a submatriz é: 
[[8 0]
 [6 6]]

62


#### Capítulo 1 Atribuição
##### Crie uma matriz nula de tamanho 10, mas o quinto valor que é 1
##### Inverta um array criado acima (o primeiro elemento se torna o último)
##### Crie uma matriz 3x3 com valores que variam de 0 a 8
##### Encontre índices de elementos diferentes de zero de [1,2,0,0,4,0]
##### Crie uma matriz 3x3x3 com valores aleatórios
##### Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo e máximo
##### Crie um vetor aleatório de tamanho 30 e encontre o valor médio
##### Crie uma matriz 2d com 1 na borda e 0 dentro
##### Multiplique uma matriz 5x3 por uma matriz 3x2 (produto da matriz real)
##### Extraia a parte inteira de uma matriz aleatória
##### Crie uma matriz 5x5 com valores de linha variando de 0 a 4
##### Crie um vetor aleatório de tamanho 10 e ordene-o
##### Considere dois arrays aleatórios A e B, verifique se eles são iguais
##### Como saber se um determinado array 2D tem colunas nulas?
##### Considerando uma matriz de quatro dimensões, como obter a soma dos dois últimos eixos de uma só vez?
##### Considere um array de dimensão (5,5,3), como multiplicá-lo por um array com dimensões (5,5)?
##### Extraia todos os blocos 3x3 contíguos de uma matriz 10x10 aleatória
##### Considere uma matriz de 16x16, como obter a soma de blocos (o tamanho do bloco é 4x4)?

In [18]:
# Primeiro
ma1 = np.zeros(10)
print ('A matriz é: \n%s\n'%ma1)
m1_5 = ma1
m1_5[6] = 1
print ('A matriz alterada é: \n%s\n'%m1_5)

A matriz é: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

A matriz alterada é: 
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]



In [19]:
# Segundo
vec1 = m1_5[::-1]
print (vec1)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


In [23]:
# Teceiro
ma = np.array([[0,1,2],[3,4,5],[6,7,8]])
print('a matriz 3x3 é: \n%s\n'%ma)

a matriz 3x3 é: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [25]:
# Quarto
ma = np.array([1,2,0,0,4,0])
print('a matriz é: \n%s\n'%ma)
idx = [0,1,4]
vec = ma[idx]
print('os numeros encontrados são: \n%s\n'%vec)

a matriz é: 
[1 2 0 0 4 0]

os numeros encontrados são: 
[1 2 4]



In [28]:
# Quinto
ma = np.random.random(size=(3,3))
print('a matriz é: \n%s\n'%ma)

a matriz é: 
[[0.52686945 0.47415361 0.31792434]
 [0.81461819 0.83657804 0.30353939]
 [0.81065328 0.84782366 0.25729835]]



In [29]:
# Sexto
ma = np.random.random(size=(10,10))
vec1 = np.max(ma)
vec2 = np.min(ma)
print('a matriz original é: \n%s\n'%ma)
print('o valor máximo da matriz é: \n%s\n'%vec1)
print('o valorm minimo da matriz é: \n%s\n'%vec2)

a matriz original é: 
[[4.31092034e-01 8.71610437e-01 9.16561478e-01 1.36976826e-01
  5.16741177e-01 4.18717680e-01 6.16507049e-01 1.82599271e-01
  1.71781548e-01 1.28479340e-01]
 [8.80567591e-01 7.80546841e-01 1.68975542e-01 7.44652673e-01
  4.30505752e-01 6.06741748e-01 1.88845679e-01 6.71540618e-01
  5.68682948e-01 5.05393117e-01]
 [2.82416779e-01 7.63659877e-01 8.40452551e-01 8.50267622e-01
  9.26831077e-01 8.23965331e-01 4.36957582e-01 4.50469903e-01
  9.55337525e-01 9.15358036e-01]
 [6.94979848e-01 7.77450233e-01 9.88414928e-01 5.22122777e-01
  3.76299344e-02 4.63990326e-01 8.27375514e-01 3.32607034e-01
  8.73763066e-04 2.78451801e-01]
 [2.37621511e-01 1.41099597e-01 1.05204683e-01 3.13436358e-01
  9.33748177e-01 8.65645270e-01 6.39994124e-01 5.30945487e-01
  9.35700759e-02 6.50498921e-01]
 [6.83730717e-01 3.17337321e-01 6.62177650e-01 5.34756083e-01
  2.32772308e-01 5.70149334e-01 7.59683039e-01 6.96289011e-01
  1.92905306e-01 5.27027787e-01]
 [9.71475929e-01 1.89922599e-01 2.21

In [30]:
# Séticmo
vec= np.random.random(size=(1,30))
vec1 = np.mean(vec)
print('o vetor é: \n%s\n'%vec)
print('a média é: \n%s\n'%vec1)

o vetor é: 
[[0.44730826 0.49131606 0.69393247 0.65015797 0.21714903 0.41395384
  0.40555241 0.72285885 0.97973576 0.19113314 0.2671354  0.89367175
  0.14350542 0.98572858 0.91843981 0.78639674 0.61856002 0.29802699
  0.31296487 0.48091278 0.22579024 0.42961243 0.38813111 0.97826243
  0.10359984 0.23833541 0.84634489 0.09817615 0.05398518 0.23819884]]

a média é: 
0.4839625549429737



In [31]:
# Oitavo
ma = np.array([[1,1,1],[1,0,1],[1,1,1]])
print(ma)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [34]:
# Nono
ma = np.random.randint(0,6,(5,3))
ma1 = np.random.randint(7,13,(3,2))
print('a matriz 1 é: \n%s\n'%ma)
print('a matriz 2 é: \n%s\n'%ma1)
print('a multiplicação das matrizes são: \n%s\n'%np.dot(ma,ma1))

a matriz 1 é: 
[[4 2 3]
 [1 2 3]
 [2 5 5]
 [4 1 1]
 [3 2 2]]

a matriz 2 é: 
[[ 7 12]
 [11  8]
 [ 7  7]]

a multiplicação das matrizes são: 
[[ 71  85]
 [ 50  49]
 [104  99]
 [ 46  63]
 [ 57  66]]



In [35]:
# Décimo
ma = np.random.randint(0,9,(3,3))
print(ma)


[[1 1 2]
 [2 1 8]
 [5 6 1]]


In [39]:
# Décimo primeiro
ma = np.random.randint(0,5,(5,5))
print(ma)

[[0 0 2 2 2]
 [0 1 0 1 2]
 [0 3 4 4 3]
 [3 1 3 4 2]
 [4 3 1 1 1]]


In [47]:
# Décimo segundo
ma = np.random.randint(0,10,(1,10))
print(ma)
vec = np.sort(ma)
print(vec)

[[5 4 6 5 3 7 8 9 3 6]]
[[3 3 4 5 5 6 6 7 8 9]]
